# Generated by Django 3.0.6 on 2020-05-21 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funolympics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduleDate', models.DateTimeField(auto_now_add=True)),
                ('scheduleFacility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funolympics.Facility')),
                ('scheduleVenue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funolympics.Venue')),
            ],
        ),
    ]
