# Generated by Django 3.0.6 on 2020-05-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funolympics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogimage',
            field=models.ImageField(upload_to='static/images/blogimages/'),
        ),
    ]
