# Generated by Django 3.0.6 on 2020-05-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funolympics', '0002_auto_20200522_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facilityimage',
            field=models.ImageField(upload_to='static/images/facilityimages/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lessonimage',
            field=models.ImageField(null=True, upload_to='static/images/lessonimages/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='static/images/profilepic/'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='sportimage',
            field=models.ImageField(upload_to='static/images/sportimages/'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venueimage',
            field=models.ImageField(upload_to='static/images/venueimages/'),
        ),
    ]
