# Generated by Django 3.0.6 on 2020-05-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funolympics', '0003_auto_20200522_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lessonimage',
            field=models.ImageField(upload_to='static/images/lessonimages/'),
        ),
    ]
